/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TypeTypeImport } from './routes/type/$type'
import { Route as PokemonNameImport } from './routes/pokemon/$name'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TypeTypeRoute = TypeTypeImport.update({
  path: '/type/$type',
  getParentRoute: () => rootRoute,
} as any)

const PokemonNameRoute = PokemonNameImport.update({
  path: '/pokemon/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/$name': {
      id: '/pokemon/$name'
      path: '/pokemon/$name'
      fullPath: '/pokemon/$name'
      preLoaderRoute: typeof PokemonNameImport
      parentRoute: typeof rootRoute
    }
    '/type/$type': {
      id: '/type/$type'
      path: '/type/$type'
      fullPath: '/type/$type'
      preLoaderRoute: typeof TypeTypeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PokemonNameRoute,
  TypeTypeRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pokemon/$name",
        "/type/$type"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pokemon/$name": {
      "filePath": "pokemon/$name.tsx"
    },
    "/type/$type": {
      "filePath": "type/$type.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
